# Copyright (c) 2025, Palo Alto Networks
#
# Licensed under the Polyform Internal Use License 1.0.0 (the "License");
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at:
#
# https://polyformproject.org/licenses/internal-use/1.0.0
# (or)
# https://github.com/polyformproject/polyform-licenses/blob/76a278c4/PolyForm-Internal-Use-1.0.0.md
#
# As far as the law allows, the software comes as is, without any warranty
# or condition, and the licensor will not be liable to you for any damages
# arising out of these terms or the use or nature of the software, under
# any kind of legal claim.

"""
AISec API service

OpenAPI Specification for the AI Runtime Security API service

The version of the OpenAPI document: 0.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from aisecurity.generated_openapi_client.models.error import Error


class TestError(unittest.TestCase):
    """Error unit tests stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self) -> Error:
        """Test Error
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included
        """
        # uncomment below to create an instance of `Error`

        return Error(status_code=404, message="Not found")

    def testError(self):
        """Test Error"""
        inst_req_only = self.make_instance()
        # Assert instance type
        self.assertIsInstance(inst_req_only, Error)

        # Assert attribute values
        self.assertEqual(inst_req_only.status_code, 404)
        self.assertEqual(inst_req_only.message, "Not found")


if __name__ == "__main__":
    unittest.main()
