# coding: utf-8
"""
AISec API service
OpenAPI Specification for the AI Runtime Security API service
The version of the OpenAPI document: 0.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)
Do not edit the class manually.
"""  # noqa: E501

import unittest
from aisecurity.generated_openapi_client.models.prompt_detection_details import PromptDetectionDetails
from aisecurity.generated_openapi_client.models.topic_guard_rails import TopicGuardRails


class TestPromptDetectionDetails(unittest.TestCase):
    """PromptDetectionDetails unit test stubs"""

    def make_instance(self, include_optional) -> PromptDetectionDetails:
        """Test PromptDetectionDetails
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""

        if include_optional:
            return PromptDetectionDetails(
                topic_guardrails_details=TopicGuardRails(
                    allowed_topics=["technology", "science", "education"],
                    blocked_topics=["violence", "illegal_activities"],
                )
            )
        else:
            return PromptDetectionDetails()

    def testPromptDetectionDetails(self):
        """Test PromptDetectionDetails"""
        # Test required only
        inst_req_only = self.make_instance(include_optional=False)
        self.assertIsInstance(inst_req_only, PromptDetectionDetails)

        # Test required and optional
        inst_req_and_optional = self.make_instance(include_optional=True)
        self.assertIsInstance(inst_req_and_optional, PromptDetectionDetails)
        self.assertIsInstance(inst_req_and_optional.topic_guardrails_details, TopicGuardRails)
        self.assertEqual(len(inst_req_and_optional.topic_guardrails_details.allowed_topics), 3)
        self.assertIn("technology", inst_req_and_optional.topic_guardrails_details.allowed_topics)
        self.assertEqual(len(inst_req_and_optional.topic_guardrails_details.blocked_topics), 2)
        self.assertIn("violence", inst_req_and_optional.topic_guardrails_details.blocked_topics)


if __name__ == "__main__":
    unittest.main()
