# Copyright (c) 2025, Palo Alto Networks
#
# Licensed under the Polyform Internal Use License 1.0.0 (the "License");
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at:
#
# https://polyformproject.org/licenses/internal-use/1.0.0
# (or)
# https://github.com/polyformproject/polyform-licenses/blob/76a278c4/PolyForm-Internal-Use-1.0.0.md
#
# As far as the law allows, the software comes as is, without any warranty
# or condition, and the licensor will not be liable to you for any damages
# arising out of these terms or the use or nature of the software, under
# any kind of legal claim.

"""
AISec API service

OpenAPI Specification for the AI Runtime Security API service

The version of the OpenAPI document: 0.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from aisecurity.generated_openapi_client.models.agent_entry_object import (
    AgentEntryObject,
)
from aisecurity.generated_openapi_client.models.agent_report_object import (
    AgentReportObject,
)


class TestAgentReportObject(unittest.TestCase):
    """AgentReportObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentReportObject:
        """Test AgentReportObject
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included
        """
        # uncomment below to create an instance of `AgentReportObject`

        if include_optional:
            return AgentReportObject(
                model_verdict="test_model_verdict",
                agent_framework="test_agent_framework",
                agent_patterns=[
                    AgentEntryObject(
                        category_type="test_category",
                        verdict="test_verdict",
                    )
                ],
            )
        else:
            return AgentReportObject()

    def testAgentReportObject(self):
        """Test AgentReportObject"""
        inst_req_only = self.make_instance(include_optional=False)
        self.assertIsInstance(inst_req_only, AgentReportObject)
        self.assertEqual(inst_req_only.model_verdict, None)
        self.assertEqual(inst_req_only.agent_framework, None)
        self.assertEqual(inst_req_only.agent_patterns, None)

        inst_req_and_optional = self.make_instance(include_optional=True)
        self.assertIsInstance(inst_req_and_optional, AgentReportObject)
        self.assertEqual(inst_req_and_optional.model_verdict, "test_model_verdict")
        self.assertEqual(inst_req_and_optional.agent_framework, "test_agent_framework")
        self.assertIsInstance(inst_req_and_optional.agent_patterns, list)
        self.assertEqual(len(inst_req_and_optional.agent_patterns), 1)
        self.assertEqual(inst_req_and_optional.agent_patterns[0].category_type, "test_category")
        self.assertEqual(inst_req_and_optional.agent_patterns[0].verdict, "test_verdict")


if __name__ == "__main__":
    unittest.main()
