# Copyright (c) 2025, Palo Alto Networks
#
# Licensed under the Polyform Internal Use License 1.0.0 (the "License");
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at:
#
# https://polyformproject.org/licenses/internal-use/1.0.0
# (or)
# https://github.com/polyformproject/polyform-licenses/blob/76a278c4/PolyForm-Internal-Use-1.0.0.md
#
# As far as the law allows, the software comes as is, without any warranty
# or condition, and the licensor will not be liable to you for any damages
# arising out of these terms or the use or nature of the software, under
# any kind of legal claim.

"""
AISec API service

OpenAPI Specification for the AI Runtime Security API service

The version of the OpenAPI document: 0.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from aisecurity.generated_openapi_client.models.prompt_detected import PromptDetected


class TestPromptDetected(unittest.TestCase):
    """PromptDetected unit tests stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptDetected:
        """Test PromptDetected
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included
        """
        # uncomment below to create an instance of `PromptDetected`

        if include_optional:
            return PromptDetected(url_cats=True, dlp=True, injection=True)
        else:
            return PromptDetected()

    def testPromptDetected(self):
        """Test PromptDetected"""
        prompt_detected = self.make_instance(include_optional=False)
        prompt_detected_optional = self.make_instance(include_optional=True)
        # Assertions for non-optional instance
        self.assertIsInstance(prompt_detected, PromptDetected)
        self.assertFalse(prompt_detected.url_cats)
        self.assertFalse(prompt_detected.dlp)
        self.assertFalse(prompt_detected.injection)

        # Assertions for optional instance
        self.assertIsInstance(prompt_detected_optional, PromptDetected)
        self.assertTrue(prompt_detected_optional.url_cats)
        self.assertTrue(prompt_detected_optional.dlp)
        self.assertTrue(prompt_detected_optional.injection)

        # Additional assertions to ensure correct behavior
        self.assertNotEqual(prompt_detected, prompt_detected_optional)
        self.assertEqual(prompt_detected, PromptDetected())
        self.assertEqual(
            prompt_detected_optional,
            PromptDetected(url_cats=True, dlp=True, injection=True),
        )


if __name__ == "__main__":
    unittest.main()
