# coding: utf-8
"""
AISec API service
OpenAPI Specification for the AI Runtime Security API service
The version of the OpenAPI document: 0.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)
Do not edit the class manually.
"""  # noqa: E501

import unittest
from aisecurity.generated_openapi_client.models.cg_report_object import CgReportObject


class TestCgReportObject(unittest.TestCase):
    """CgReportObject unit test stubs"""

    def make_instance(self, include_optional) -> CgReportObject:
        """Test CgReportObject
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""

        if include_optional:
            return CgReportObject(
                status="completed", explanation="Code analysis completed successfully", category="security_scan"
            )
        else:
            return CgReportObject()

    def testCgReportObject(self):
        """Test CgReportObject"""
        # Test required only
        inst_req_only = self.make_instance(include_optional=False)
        self.assertIsInstance(inst_req_only, CgReportObject)

        # Test required and optional
        inst_req_and_optional = self.make_instance(include_optional=True)
        self.assertIsInstance(inst_req_and_optional, CgReportObject)
        self.assertEqual(inst_req_and_optional.status, "completed")
        self.assertEqual(inst_req_and_optional.explanation, "Code analysis completed successfully")
        self.assertEqual(inst_req_and_optional.category, "security_scan")


if __name__ == "__main__":
    unittest.main()
